### ISSUE TITLE
Events - On: Cannot remove handler added by `attachEvent` (IE8+)

### ISSUE THREAD

**Issue by sompylasar** [HubSpot/youmightnotneedjquery#104]
http://youmightnotneedjquery.com/#on

``` js
function addEventListener(el, eventName, handler) {
  if (el.addEventListener) {
    el.addEventListener(eventName, handler);
  } else {
    el.attachEvent('on' + eventName, function(){
      handler.call(el);
    });
  }
}

addEventListener(el, eventName, handler);
```

The proposed implementation passes a new function to `attachEvent` instead of the given `handler`. This new function has no chance to be removed with the corresponding `detachEvent`.

**Comment by ahimta** [comment]
Unfortunately, for some reason I can't access http://youmightnotneedjquery.com/#on
However, as I remember you're right.

I am working right now on porting a jQuery plugin to vanilla Javascript and I use a separate helper function to wrap the handler so that I can remove the handler. You can find it [here](https://github.com/Ahimta/intl-tel-input/blob/22fc9d931242f21b6d0bab540018b5953af4e918/src/js/intlTelInput.js.ejs#L191)

Furthermore, there's a more subtle bug that I encountered when testing on IE8.
The bug is simply that the event isn't passed to the wrapped function.

``` javascript
function wrapHandler(element, fn) {

  // take the event as a parameter and pass it to `fn`
  // otherwise the `event` parameter will be `undefined` in the wrapped function
  return function(event) {
    fn.call(element, event);
  };

}
```

**Comment by sompylasar** [comment]
> Furthermore, there's a more subtle bug that I encountered when testing on IE8.
> The bug is simply that the event isn't passed to the wrapped function.

Yes, this is a bad bug, too.
