### ISSUE TITLE
Where is $("#myelement")

### ISSUE THREAD

**Issue by stevage** [HubSpot/youmightnotneedjquery#188]
This is the most common thing that I (and probably many others) do with jQuery, that really doesn't need it: `$('#myelement')`. The equivalent is roughly `document.getElementById('myelement')`

**Comment by mdss-single** [comment]
here
http://youmightnotneedjquery.com/#find_elements

**Comment by stevage** [comment]
Huh! I looked, I really did. It would seem logical to me to have it in a special place, before all the other sections, because almost everything assumes you have already found an element somehow.

**Comment by brndto** [comment]
I personally don't agree, it's fine where it is, if you didn't find it the first time you didn't really read through the entire thing, which is bad because there's a lot of vanilla flavoured goodness in there.
Although you mention getElementById as it's equivalent when in reality, it's document.querySelector / document.querySelectorAll for IE8+. (Which is why jQuery uses both querySelector and getElementById afaik)

You can also use something like this to keep the shorthand $(selector)
const $ = (selector) => (selector[0] === '#' ? document.querySelector(selector) : document.querySelectorAll(selector));
