### ISSUE TITLE
Drop IE Support

### ISSUE THREAD

**Issue by 100Errors** [HubSpot/youmightnotneedjquery#191]
With the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) http requests are a little bit easier than with xmlhttprequest, maybe you could build that also in that website?

**Comment by nickserv** [comment]
IE no longer develops new features, it should be replaced with Edge (or alternatively it could be treated as a new "version" in the slider).

**Comment by radiocity** [comment]
Bad idea. For example, our corp. website still has ~11% of unique visitors with IE browser.

**Comment by nickserv** [comment]
This can still be improved by adding IE 11 or Edge.

**Comment by 7fe** [comment]
IE11 will be around for quite a bit longer.  There are corporate applications that requires IEs old features.

For that reason I vote to remove all IEs but IE11.  Remove the others I don't care but IE11 is not going away for quite a bit longer.

**Comment by jstnbr** [comment]
Please don't remove IE. I enjoy seeing alternatives back to at least IE10. I'm sure other developers enjoy seeing IE8 and IE9 support as well.

"IE no longer develops new features" -stated above, this is the exact reason developers want to know how to support them.

**Comment by FranklinYu** [comment]
Rather than *dropping* IE, how about *adding* Edge? Currently we can select among IE 9, 10, 11. How about changing it to IE 9, 10, 11, Edge? That way both enterprise user and ordinary developer can be happy.

IE 11 should be there as long as Microsoft still supports it.

Edit: I forgot that I mentioned IE 11 a year ago in #180.

**Comment by nickserv** [comment]
I like the idea of adding Edge, but for practical purposes it's actually more up to date than Safari, so I think at that point it should just target modern browsers and IE.

**Comment by nickserv** [comment]
Alternatively, can we please consider merging #193 for now? I still find the information on this site helpful despite not targeting more modern browsers than IE 10. However, it's frustrating to have to remember to manually switch from IE 9 to IE 10 (which are no longer by Microsoft) every time I visit it or send someone a link to get code that's friendlier for modern browsers, especially since many modern projects don't target IE anyway.

**Comment by FranklinYu** [comment]
I thought this project was dead because PRs stay open without feedback. Thanks @FranDias telling us that it is still alive.

@nickmccurdy Then how about this:

> Do you need to support IE 11? `[ ]` yes `[ ]` no

Or maybe

> What are you targeting? `[ ]` IE 11 and modern browsers `[ ]` only modern browsers
>
> Note: "modern browsers" include Chrome, Firefox, Safari and Edge.

**Comment by FranDias** [comment]
@franklinyu heh, I still read every comment but since this project isn't core to our business/anyone @ hubspot's workday so it's 🤷‍♂️ .

A lot of the open PR's were just there way back when so it's a backlog of stuff to look though. If someone cares enough to open an issue of priorities they care about I'm happy to go though to consider.

**Comment by FranklinYu** [comment]
@FranDias The top priority in my mind is #193 which is already merged 🎉 

I'm looking at PRs sorted by "Most reactions - upvote". #128 looks good; #152 would be good with @sukima's suggestion.

**Comment by devsuperman** [comment]
YEEEEEEEEEESSSS! DROP THE IE SUPORT AND 'FETCH' EVERYWHERE!! xD

**Comment by victornpb** [comment]
Anyone that has been around jquery or is considering using it, is probably Because they have to support ancient browsers.

I don’t see the purpose of removing IE, since it defeats the purpose of this site. This entire site is pointless if you’re targeting evergreen browsers, so you don’t need jquery nor this site.

My 2c

**Comment by victornpb** [comment]
Btw edge is switching to blink, if it wasn’t modern enough

**Comment by nickserv** [comment]
This site is meant to show legacy jQuery users that they don’t need it to target modern browsers. If you don’t need support IE or even Edge, this site becomes even more useful. Still, the site should be updated to focus on all widely supported features in evergreeen browsers, not just IE and Edge. Also in future releases of Edge it will just act like Chromium browsers, meaning specifically supporting Edge isn’t necessary as long as you target Chromium.

**Comment by FranDias** [comment]
Locking because I don't believe anything added to this closed issue will be a positive use of time.
