### ISSUE TITLE
Add 'autofocus' on search input and make it focusable with '/' key

### ISSUE THREAD

**Issue by rulrok** [HubSpot/youmightnotneedjquery#227]
The fact that the search input is missing the `autofocus` attribute is a big UX problem :crying_cat_face: 

Also, as it is current practice on many sites targeted for developers as I see, make it focusable when typing `/`.
That comes from `vim` shortcuts I believe.

**Comment by Abbondanzo** [comment]
Since this site relies heavily on anchor tags, autofocusing the search input would conflict with that behavior. The autofocus takes priority over anchor tags, and will skip the intro content in the fold.

However, I've added this keyboard shortcut in #308. That will bring the search input into the fold wherever the developer is
