### ISSUE TITLE
sidebar as an index

### ISSUE THREAD

**Issue by ekremkaraca** [HubSpot/youmightnotneedjquery#33]
It's better to have a sidebar (whether left or right side of the website) as an index to access subjects faster. What would you say about that?

**Comment by tomByrer** [comment]
+1 I like [Lo-Dash's docs](http://lodash.com/docs) for this reason.

**Comment by zackbloom** [comment]
Yep, would be cool.  We'll think about it as we iterate on the design.  The other option is to just lean even heavier into search.

**Comment by tomByrer** [comment]
Maybe a pop-out to keep the design minimal.

**Comment by ekremkaraca** [comment]
Maybe something like Pageslide could be made without destroying existing design :star2: 
http://srobbin.com/jquery-plugins/pageslide/

**Comment by Sarke** [comment]
Can we re-open this?  It makes no sense to not have an index IMO.

Yes, I can use the search if I know what I'm looking for, but if not then you end up scrolling through.

**Comment by ekremkaraca** [comment]
yep, it's been 5 years but for the page, it's still same. maybe sidebar is too much for this but at least a toc as @Sarke suggests. as the opener of this issue, i want it to be reopened and discussed until we find a better solution.

**Comment by FranDias** [comment]
Hey I think it seems reasonable and I could see a git book or underscore stay page replacing the current design. But due to https://github.com/HubSpot/youmightnotneedjquery/issues/200 I’m not reopening any issues.

Could you comment on that issue how often you reference this? I’m always weighing the effort to rebuild/value
