### ISSUE TITLE
document.body.scrollTop is not portable

### ISSUE THREAD

**Issue by zackbloom** [HubSpot/youmightnotneedjquery#85]

**Comment by rstacruz** [comment]
It might be a good idea to create an entry for scrollTop:

``` js
// jQuery
$(window).scrollTop();

// plain ol' JavaScript
var scrollTop =
  (typeof window.pageYOffset !== 'undefined') ?
    function() { return window.pageYOffset; } :
  (document.documentElement && document.documentElement.clientHeight) ?
    function() { return document.documentElement.scrollTop; } :
  function() { return document.body.scrollTop; };
```

**Comment by rstacruz** [comment]
documentElement.scrollTop is for Webkit, and body.scrollTop is for Gecko. Or was it the other way around? :)

...and pageYOffset isn't implemented but is in the standard: https://developer.mozilla.org/en-US/docs/Web/API/Window.scrollY

**Comment by rstacruz** [comment]
Also, the _Offset_ section has a reference to `document.body.scrollTop` that needs to be updated accordingly.

**Comment by Krinkle** [comment]
For IE9+, `pageYOffset` is reliably available across browsers.

The "Offset" section should be fixed to use `window.pageYOffset` instead, because the currently recommended alternative **is broken**.

For a request to add a separate section dedicated to `scrollTop`, see https://github.com/HubSpot/youmightnotneedjquery/issues/187.
