### ISSUE TITLE
outerHTML jQuery example is ridiculous

### ISSUE THREAD

**Issue by lolmaus** [HubSpot/youmightnotneedjquery#95]
This:

``` js
$('<div>').append($(el).clone()).html();
```

is absolutely ridiculous. Having jQuery doesn't forbid you from using native methods where appropriate.

Any sane jQuery user would do `el.outerHTML` rather than a barrel roll you're suggesting.

And if you start with `$el` rather then `el`, the reasonable way to do it would be:

``` js
$el.get(0).outerHTML;
```

or

``` js
$el[0].outerHTML;
```

Don't be ridiculous trying to prove your point.

**Comment by zackbloom** [comment]
As much as I'd like to say you're right, one big reason for creating the site is simply because many people are not aware of the native DOM methods available.  The site is not about making a point, it's about showing people who might think that `$('<div>').append($(el).clone()).html();` was the correct solution (based on a search in the jQuery docs), that there's another way.

In other words, our goal is to promote exactly what you're advocating.  This is not about showing that jQuery is bad, it's about showing that the browser is all you need in many cases, which seems to be your opinion as well.
